const data = {
  products: [
    {
      _id: "1",
      name: "Women Floral Print Anarkali Kurta with Pant and Dupatta",
      category: "Weston dress",
      image: "images/img_1.jpg",
      price: 120,
      brand: "Allen Solly",
      rating: 4.5,
      numReview: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "AASK Kurta for Women Dress",
      category: "Weston dress",
      image: "images/img_2.jpg",
      price: 90,
      brand: "Allen Solly",
      rating: 4.5,
      numReview: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: " AAYU FIT & Flare Georgette Calf Length Dress for Women",
      category: "Weston dress",
      image: "images/img_3.jpg",
      price: 180,
      brand: "Allen Solly",
      rating: 4.5,
      numReview: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Sheetal Associates Women Casual Regular Sleeves Crepe Solid Fit and Flare Dress",
      category: "Weston dress",
      image: "images/img_4.jpg",
      price: 120,
      brand: "Allen Solly",
      rating: 4.5,
      numReview: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "QUEEN ELLIE Women's A-Line Midi Dress",
      category: "Weston dress",
      image: "images/img_5.jpg",
      price: 100,
      brand: "Allen Solly",
      rating: 4.5,
      numReview: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Western Dresses for Women",
      category: "Weston dress",
      image: "images/img_6.jpg",
      price: 70,
      brand: "Allen Solly",
      rating: 4.5,
      numReview: 10,
      description: "high quality product",
    },
    {
      _id: "7",
      name: "QUEEN ELLIE Women's A-Line Midi Dress",
      category: "Weston dress",
      image: "images/img_5.jpg",
      price: 200,
      brand: "QUEEN",
      rating: 4.5,
      numReview: 10,
      description: "high quality product",
    },
    {
      _id: "8",
      name: "AASK Kurta for Women Dress",
      category: "Weston dress",
      image: "images/img_2.jpg",
      price: 230,
      brand: "Allen Solly",
      rating: 4.5,
      numReview: 10,
      description: "high quality product",
    },
  ],
};
export default data;
